# Generated by Django 4.2.7 on 2025-09-25 17:01

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin')], default='patient', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('crm', models.CharField(max_length=15, unique=True)),
                ('cpf', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreTriage',
            fields=[
                ('pre_triage_id', models.AutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('web', 'Web'), ('whatsapp', 'WhatsApp'), ('totem', 'Totem')], max_length=30)),
                ('symptoms_text', models.TextField(blank=True, null=True)),
                ('symptoms_audio', models.TextField(blank=True, null=True)),
                ('symptoms_image', models.TextField(blank=True, null=True)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20, null=True)),
                ('triage_code', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('revisao', 'Revisão'), ('finalizado', 'Finalizado')], default='pendente', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_triages', to='triage.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TriageReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('final_risk_level', models.CharField(blank=True, max_length=20, null=True)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='triage.doctor')),
                ('pre_triage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='triage.pretriage')),
            ],
        ),
        migrations.CreateModel(
            name='TriageMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('patient', 'Patient'), ('ai', 'AI'), ('doctor', 'Doctor')], max_length=20)),
                ('sender_id', models.IntegerField(blank=True, null=True)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('message_media', models.TextField(blank=True, null=True)),
                ('audio_transcript', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pre_triage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='triage.pretriage')),
            ],
        ),
        migrations.CreateModel(
            name='TriageHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('final_risk', models.CharField(blank=True, max_length=20, null=True)),
                ('outcome', models.CharField(blank=True, max_length=100, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='triage.doctor')),
                ('pre_triage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='triage.pretriage')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('patient_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=5, null=True)),
                ('allergy', models.CharField(blank=True, max_length=200, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='triage.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='enviado', max_length=20)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='triage.doctor')),
                ('pre_triage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='triage.pretriage')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('metric_id', models.AutoField(primary_key=True, serialize=False)),
                ('response_time', models.DurationField(blank=True, null=True)),
                ('reliability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pre_triage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='triage.pretriage')),
            ],
        ),
    ]
