# Generated by Django 4.2.7 on 2025-10-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0003_conversationsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationsession',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
