# Generated by Django 4.2.7 on 2025-10-31 11:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0004_alter_conversationsession_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('analysis', models.TextField(help_text='Análise detalhada dos sintomas do paciente')),
                ('ai_confidence', models.IntegerField(blank=True, help_text='Confiança da IA na análise (0-100)', null=True)),
                ('risk_level', models.IntegerField(blank=True, help_text='Nível de risco calculado (0-100)', null=True)),
                ('confidence_score', models.IntegerField(blank=True, help_text='Score de confiança geral (0-100)', null=True)),
                ('next_question', models.TextField(blank=True, help_text='Próxima pergunta a ser feita ao paciente', null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='triage.conversationsession')),
            ],
            options={
                'verbose_name': 'Análise de Triagem',
                'verbose_name_plural': 'Análises de Triagem',
                'db_table': 'triage_triageanalysis',
                'ordering': ['-created_at'],
            },
        ),
    ]
