# Generated by Django 4.2.7 on 2025-10-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0005_triageanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretriage',
            name='status',
            field=models.CharField(
                choices=[
                    ('pendente', 'Pendente'),
                    ('revisao', 'Revisão'),
                    ('finalizado', 'Finalizado')
                ],
                default='pendente',
                max_length=60
            ),
        ),
    ]
